name: Build and Publish Docker Image

# This action builds a docker image with name `image-name` and
# pushes it to the MCG Github Container registry

on:
  workflow_call:
    inputs:
      image-name: # The name of the image to build
        required: true
        type: string
      context-path: # The path of 
        required: false
        type: string
      service-name: # The name of the service (for logging)
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push {{ service-name }} Docker Image
        uses: docker/build-push-action@v5
        with:
          context: service/{{ context-path }}
          push: true
          tags: ghcr.io/marquescg/{{ image-name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

