name: Update manifests

# This action updates the image tags for the kustomization files within homelab-infra

on:
  workflow_call:
    inputs:
      service-name: # The name of the service to update (within homelab)
        required: true
        type: string
      deploy-env: # The environment to update (dev|production)
        required: true
        type: string
      branch-name: # The name of the branch to pull from
        required: true
        type: string
      manifest-repo: # The github repo that houses the manifests
        required: false
        type: string
        default: tylermarques/homelab-infra
      deploy-src: # The path do the deployment files
        required: false
        type: string
        default: deploy
    secrets:
      HOMELAB_TOKEN:
        required: true

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homelab
        uses: actions/checkout@v4
        with:
            repository: ${{ inputs.manifest-repo }}
            ref: main
            token: ${{ secrets.HOMELAB_TOKEN }}
            path: homelab-infra/
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: source/

      - name: Update Manifests
        run: |
          cd homelab-infra
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cp -R ../source/${{ inputs.deploy-src }}/${{ inputs.deploy-env }} apps/${{ inputs.service-name }}
          yq e '.images[].newTag = "'${{ github.sha }}'"' apps/${{ inputs.service-name }}/${{ inputs.deploy-env }}/kustomization.yaml -i
          git add .
          git commit -am 'Push from ${{ github.actor }} to ${{ github.repository }}'
          git push
