name: Update manifests

# This action updates the image tags for the kustomization files within homelab-infra

on:
  workflow_dispatch: # Allows manual runs if needed
    inputs:
      service-name: # The name of the service to update (within homelab)
        required: true
        type: string
      service-env: # The environment to update (dev|production)
        required: true
        type: string
      branch-name: # The name of the branch to pull from
        required: true
        type: string
  workflow_call:
    inputs:
      service-name: # The name of the service to update (within homelab)
        required: true
        type: string
      service-env: # The environment to update (dev|production)
        required: true
        type: string
      branch-name: # The name of the branch to pull from
        required: true
        type: string

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homelab
        run:
          git clone https://${{ secrets.OWEN_TOKEN }}@github.com/owenwaldron/homelab-infra-test.git homelab-infra
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}
          path: source/

      - name: Update Manifests
        run: |
          cd homelab-infra
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cp -R ../source/deploy/${{ inputs.service-env }} apps/${{ inputs.service-name }}
          yq e '.images[].newTag = "'${{ github.sha }}'"' apps/${{ inputs.service-name }}/${{ inputs.service-env }}/kustomization.yaml -i
          git commit -am 'Push from ${{ github.actor }} to ${{ github.repository }}'
          git push
