name: Initialize Microservice

# This copies all manifests to homelab infra

on:
  workflow_call: # Allows manual runs if needed
    inputs:
      service-name: # The name of the service to update (within homelab)
        required: true
        type: string
      branch-name: # (default: main) The name of the branch to pull from
        required: false
        default: main
        type: string

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homelab
        uses: actions/checkout@v4
        with:
          repository: tylermarques/homelab-infra
          ref: main
          token: ${{ secrets.HOMELAB_TOKEN }}
          path: homelab-infra/
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: main/

      - name: Copy Manifests
        run: |
          cd homelab-infra
          ls -lha
          apt update && apt install -y yq
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cp -R ../main/deploy apps/${{ inputs.service-name }}
          git commit -am 'Initializing service ${{ inputs.service-name }} from ${{ github.actor }}'
          git push
