name: Initialize Microservice

# This copies all manifests to homelab infra

on:
  workflow_call: # Allows manual runs if needed
    inputs:
      service-name: # The name of the service to update (within homelab)
        required: true
        type: string
      branch-name: # (default: main) The name of the branch to pull from
        required: false
        default: main
        type: string
    secrets:
      HOMELAB_TOKEN:
        required: true

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homelab
        uses: actions/checkout@v4
        with:
          repository: owenwaldron/homelab-infra-test
          ref: main
          token: ${{ secrets.HOMELAB_TOKEN }}
          path: homelab-infra/
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: source/

      - name: Copy Manifests
        run: |
          cd homelab-infra
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          cp -R ../source/deploy apps/${{ inputs.service-name }}
          git add .
          git commit -am 'Initializing service ${{ inputs.service-name }} from ${{ github.actor }}'
          git push
